// ааааа тут все стилики хранятся~~ их очень много, аж хвостик закрутился~~
import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  background: {
    flex: 1,
    backgroundColor: '#140f1e',
  },
  backgroundShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(12, 8, 18, 0.5)',
  },
  orbLarge: {
    position: 'absolute',
    top: -60,
    right: -80,
    width: 220,
    height: 220,
    borderRadius: 220,
    backgroundColor: 'rgba(163, 100, 255, 0.2)',
  },
  orbSmall: {
    position: 'absolute',
    bottom: 140,
    left: -50,
    width: 180,
    height: 180,
    borderRadius: 180,
    backgroundColor: 'rgba(255, 116, 183, 0.14)',
  },
  safeArea: {
    flex: 1,
    alignItems: 'center',
  },
  safeAreaWide: {
    width: '100%',
    paddingVertical: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  appFrame: {
    flex: 1,
    width: '100%',
    backgroundColor: 'rgba(14, 10, 20, 0.72)',
  },
  appFrameWide: {
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 34,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.4,
    shadowRadius: 30,
    shadowOffset: { width: 0, height: 14 },
    elevation: 18,
  },
  screenStage: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 146,
  },
  successContent: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  page: {
    gap: 18,
  },
  phoneHeaderExact: {
    minHeight: 96,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: 'rgba(224, 221, 232, 0.64)',
    backgroundColor: 'rgba(8, 7, 14, 0.88)',
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
  },
  brandExact: {
    color: '#ffffff',
    fontSize: 34,
    fontWeight: '900',
    letterSpacing: 0.2,
  },
  searchShellExact: {
    flex: 1,
    maxWidth: 172,
    height: 46,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: 'rgba(19, 14, 28, 0.2)',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  searchInputExact: {
    flex: 1,
    paddingVertical: 0,
    color: '#0f0b15',
    fontSize: 15,
    fontWeight: '700',
  },
  catalogGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 18,
  },
  glassPanel: {
    borderRadius: 30,
    borderWidth: 2,
    borderColor: 'rgba(224, 221, 232, 0.5)',
    backgroundColor: 'rgba(38, 15, 55, 0.52)',
    padding: 16,
  },
  catalogCard: {
    borderRadius: 30,
    borderWidth: 2,
    borderColor: 'rgba(224, 221, 232, 0.52)',
    backgroundColor: 'rgba(28, 11, 45, 0.72)',
    padding: 10,
  },
  catalogCardTap: {
    gap: 12,
  },
  catalogCardBody: {
    paddingHorizontal: 4,
  },
  catalogCardTitle: {
    color: '#ffffff',
    fontSize: 23,
    fontWeight: '900',
    marginBottom: 4,
  },
  catalogCardPrice: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '900',
    marginTop: 4,
  },
  catalogButton: {
    minHeight: 44,
    borderRadius: 18,
    backgroundColor: '#ae82f4',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  catalogButtonText: {
    color: '#1d1626',
    fontSize: 18,
    fontWeight: '900',
  },
  artworkFrame: {
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(224, 221, 232, 0.42)',
    position: 'relative',
  },
  artworkImage: {
    borderRadius: 24,
  },
  artworkShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(20, 8, 28, 0.18)',
  },
  artworkShadeLight: {
    backgroundColor: 'rgba(255, 248, 243, 0.18)',
  },
  artworkAsset: {
    position: 'absolute',
  },
  artworkSticker: {
    position: 'absolute',
  },
  artworkTitleTop: {
    position: 'absolute',
    fontWeight: '900',
    textTransform: 'uppercase',
    textShadowColor: 'rgba(0,0,0,0.35)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  artworkTitleMain: {
    position: 'absolute',
    fontWeight: '900',
    textShadowColor: 'rgba(0,0,0,0.35)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  artworkTitleSub: {
    position: 'absolute',
    fontWeight: '900',
    textTransform: 'uppercase',
    textShadowColor: 'rgba(0,0,0,0.35)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  scenePill: {
    position: 'absolute',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  scenePillText: {
    color: '#ffffff',
    fontSize: 9,
    fontWeight: '800',
  },
  hitBubble: {
    position: 'absolute',
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f0a9bf',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  hitBubbleText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '900',
  },
  productRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  productRatingStars: {
    color: '#ffd14f',
    fontSize: 14,
    letterSpacing: 1,
  },
  productRatingText: {
    color: 'rgba(245, 239, 255, 0.7)',
    fontSize: 12,
  },
  heroCard: {
    borderRadius: 32,
    borderWidth: 2,
    borderColor: 'rgba(224, 221, 232, 0.56)',
    backgroundColor: 'rgba(28, 11, 45, 0.72)',
    padding: 16,
  },
  heroBody: {
    paddingHorizontal: 6,
    paddingTop: 14,
  },
  heroTitle: {
    color: '#ffffff',
    fontSize: 27,
    fontWeight: '900',
  },
  heroSubtitle: {
    color: 'rgba(235, 229, 245, 0.74)',
    fontSize: 14,
    marginTop: 6,
    marginBottom: 12,
  },
  heroPrice: {
    color: '#ffffff',
    fontSize: 26,
    fontWeight: '900',
    marginTop: 8,
  },
  heroRailSection: {
    marginTop: 4,
  },
  heroRail: {
    paddingBottom: 4,
    gap: 18,
  },
  miniPosterCard: {
    borderRadius: 24,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(224, 221, 232, 0.42)',
  },
  exactPrimaryButton: {
    alignSelf: 'stretch',
    minHeight: 64,
    borderRadius: 22,
    backgroundColor: '#ae82f4',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 14,
  },
  exactPrimaryButtonText: {
    color: '#18121f',
    fontSize: 22,
    fontWeight: '900',
  },
  exactDarkButton: {
    alignSelf: 'stretch',
    minHeight: 64,
    borderRadius: 22,
    backgroundColor: '#1d1b1d',
    borderWidth: 2,
    borderColor: 'rgba(224, 221, 232, 0.72)',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 14,
  },
  exactDarkButtonText: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '900',
  },
  favoritesPanel: {
    gap: 14,
  },
  panelHeading: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '900',
  },
  panelSubheading: {
    color: 'rgba(236, 231, 245, 0.64)',
    fontSize: 12,
    marginTop: 2,
  },
  favoriteRow: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(224, 221, 232, 0.28)',
    backgroundColor: 'rgba(26, 10, 38, 0.48)',
    padding: 10,
    gap: 10,
  },
  favoriteRowTap: {
    flexDirection: 'row',
    gap: 12,
  },
  favoriteRowPoster: {
    width: 90,
  },
  favoriteRowBody: {
    flex: 1,
    justifyContent: 'center',
  },
  favoriteRowTitle: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '900',
  },
  favoriteRowSubtitle: {
    color: 'rgba(236, 231, 245, 0.64)',
    fontSize: 12,
    marginTop: 4,
  },
  favoriteRowPrice: {
    color: '#ffffff',
    fontSize: 19,
    fontWeight: '900',
    marginTop: 10,
  },
  favoriteRowActions: {
    flexDirection: 'row',
    gap: 10,
  },
  favoriteGhostButton: {
    width: 46,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(224, 221, 232, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(18, 12, 24, 0.58)',
  },
  favoriteAddButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 16,
    backgroundColor: '#ae82f4',
    justifyContent: 'center',
    alignItems: 'center',
  },
  favoriteAddButtonText: {
    color: '#1d1626',
    fontSize: 17,
    fontWeight: '900',
  },
  cartPanel: {
    gap: 14,
    padding: 18,
  },
  cartItemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(224, 221, 232, 0.34)',
    backgroundColor: 'rgba(19, 9, 30, 0.7)',
    padding: 12,
    gap: 14,
  },
  cartThumbWrap: {
    width: 92,
    height: 92,
    borderRadius: 18,
    overflow: 'hidden',
  },
  cartThumbImage: {
    width: '100%',
    height: '100%',
  },
  cartItemBody: {
    flex: 1,
  },
  cartItemTitle: {
    color: '#ffffff',
    fontSize: 19,
    fontWeight: '900',
  },
  cartItemSubtitle: {
    color: 'rgba(236, 231, 245, 0.68)',
    fontSize: 12,
    marginTop: 4,
  },
  cartItemPrice: {
    color: '#b48cff',
    fontSize: 18,
    fontWeight: '900',
    marginTop: 14,
  },
  cartItemSide: {
    alignItems: 'flex-end',
    gap: 10,
  },
  cartRemoveButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  cartStepper: {
    minWidth: 112,
    height: 46,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(224, 221, 232, 0.54)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
  },
  cartStepperButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartStepperValue: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '900',
  },
  cartSummaryCard: {
    gap: 8,
  },
  cartSummaryTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: 8,
  },
  cartSummaryTitle: {
    color: '#ffffff',
    fontSize: 34,
    fontWeight: '900',
  },
  cartSummaryValue: {
    color: '#ffffff',
    fontSize: 26,
    fontWeight: '900',
  },
  pageHeroTitle: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '900',
    marginTop: 4,
  },
  checkoutCard: {
    gap: 12,
  },
  checkoutAddressText: {
    color: 'rgba(236, 231, 245, 0.74)',
    fontSize: 16,
    lineHeight: 24,
  },
  outlineAction: {
    alignSelf: 'flex-end',
    minWidth: 140,
    minHeight: 46,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(224, 221, 232, 0.46)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  outlineActionText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  paymentGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  paymentSwatch: {
    width: '47%',
    minHeight: 42,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(224, 221, 232, 0.46)',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    gap: 10,
  },
  paymentSwatchActive: {
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  paymentSwatchDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
  },
  paymentSwatchLabel: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  checkoutSummaryCardExact: {
    minHeight: 286,
  },
  checkoutSummaryFill: {
    marginTop: 'auto',
    gap: 2,
  },
  profileHeroCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    minHeight: 146,
  },
  profileHeroInfo: {
    flex: 1,
  },
  profileHeroTitle: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '900',
  },
  profileHeroEmail: {
    color: 'rgba(236, 231, 245, 0.68)',
    fontSize: 16,
    marginTop: 6,
  },
  profileEmptyCard: {
    minHeight: 140,
  },
  profileSettingsCard: {
    minHeight: 260,
  },
  profileSettingRow: {
    minHeight: 58,
    borderTopWidth: 1,
    borderTopColor: 'rgba(224, 221, 232, 0.26)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  profileSettingText: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '700',
  },
  successExactCard: {
    minHeight: 360,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 28,
  },
  successExactIcon: {
    width: 110,
    height: 110,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: '#8e68db',
    backgroundColor: '#1d1b1d',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 22,
  },
  successExactTitle: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '900',
    textAlign: 'center',
  },
  emptyCard: {
    alignItems: 'center',
    borderRadius: 24,
    padding: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  emptyEmoji: {
    fontSize: 34,
    marginBottom: 6,
  },
  emptyTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
  },
  emptyText: {
    marginTop: 8,
    color: 'rgba(242, 236, 255, 0.7)',
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
    marginBottom: 14,
  },
  primaryButton: {
    minHeight: 50,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ae82f4',
    borderWidth: 0,
    marginTop: 10,
    paddingHorizontal: 20,
  },
  primaryButtonText: {
    color: '#18121f',
    fontSize: 16,
    fontWeight: '900',
  },
  bottomNavExact: {
    position: 'absolute',
    left: 18,
    right: 18,
    bottom: 14,
    minHeight: 78,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: 'rgba(224, 221, 232, 0.54)',
    backgroundColor: 'rgba(15, 11, 22, 0.78)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 8,
  },
  navItemExact: {
    width: '19%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  navIconWrap: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navIconWrapActive: {
    shadowColor: '#af87ff',
    shadowOpacity: 0.55,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 0 },
    elevation: 8,
  },
  navLabelExact: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 11,
    marginTop: 4,
  },
  navLabelExactActive: {
    color: '#af87ff',
  },
  cardPressed: {
    opacity: 0.86,
    transform: [{ scale: 0.99 }],
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  summaryLabel: {
    color: 'rgba(242, 236, 255, 0.68)',
    fontSize: 13,
  },
  summaryLabelStrong: {
    color: '#fff',
    fontWeight: '800',
  },
  summaryValue: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
  },
  summaryValueAccent: {
    color: '#ff9cdb',
  },
  summaryValueStrong: {
    fontSize: 17,
    fontWeight: '900',
  },
  statusBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  statusNeutral: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  statusText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '800',
  },
  badge: {
    marginRight: 8,
    marginBottom: 8,
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  badgeCompact: {
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  badgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  offlineBanner: {
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 2,
    borderRadius: 18,
    padding: 12,
    backgroundColor: 'rgba(255, 114, 183, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(255, 114, 183, 0.22)',
  },
  offlineTitle: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
  },
  offlineText: {
    marginTop: 4,
    color: 'rgba(255, 240, 247, 0.9)',
    fontSize: 12,
    lineHeight: 17,
  },
  errorCard: {
    borderRadius: 20,
    padding: 14,
    marginTop: 4,
    backgroundColor: 'rgba(255, 114, 183, 0.14)',
    borderWidth: 1,
    borderColor: 'rgba(255, 114, 183, 0.24)',
  },
  errorTitle: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
  },
  errorText: {
    marginTop: 6,
    color: 'rgba(255, 236, 246, 0.9)',
    fontSize: 12,
    lineHeight: 17,
  },
})
